### ISSUE TITLE
Git is missing

### ISSUE THREAD

**Issue by Drezir** [carlossg/docker-maven#149]
Hello,

we have recently discovered a problem with git that was not present in the "latest" tag. I would expect it to be installed in this tag. SLIM and ALPINE versions should not include git as it is now so if you did not switch "latest" tag to some of these two variants, bring git back please.

**Comment by carlossg** [comment]
see #147

**Comment by O5ten** [comment]
I second this issue, i filed another issue that @yosifkit closed just above here towards the docker-library on the openjdk image where they swapped the base-image from build-deps, that includes git among other tools, to a oraclelinux7 image that doesn't. the Maven image depends on that project and should perhaps consider changing its dependency to something such as [adoptopenjdk](https://hub.docker.com/_/adoptopenjdk) or pre-install at the very least git. I just don't want every single person & company to build their own because that breaks standards and creates unneccessary work at this point. 

At the very least for the non-slim/non-alpine images because years of using this image in CI/CD has made us somewhat reliant on being able to tell people to use the maven version that suits them by selecting a particular docker image and not having to provision images that comes bundled with particular tools. Now, we could of course tell them to use older versions, but that only works for so long. 

I do not agree with the response in https://github.com/carlossg/docker-maven/issues/147 that the image upstream has changed it and therefore the maven image must follow. I think we'll see in the upcoming few days when companies internal docker proxies has an invalidated cache on `maven:3.6.3` and similar that there will be an outcry for having such basic tools in the non-slim image. 

Or can you provide me with a specific tag that still has `git`, `openjdk:14-jdk` and `maven:3.6.3` in it?

**Comment by carlossg** [comment]
As I said in #110 git can be added if enough people 👍 it, so far only 10 people have

To avoid duplication I'm going to close this one
There was never an openjdk 14 image that had git in it afaik
