### ISSUE TITLE
Artifact caching for Multi-stage Builds

### ISSUE THREAD

**Issue by awhitford** [carlossg/docker-maven#36]
I would love to use this for a [multi-stage build](https://docs.docker.com/engine/userguide/eng-image/multistage-build/), but [the lack of a volume mount option for docker build](https://github.com/moby/moby/issues/14080) poses a **serious inefficiency** due to the lack of artifact caching.

Are you aware of any good _alternatives_?

**Comment by mhaji** [comment]
Facing similar issue. [This proposal](https://github.com/moby/moby/issues/32507) if/when done will help address the issue.

**Comment by awhitford** [comment]
Sadly, I don't see how that `RUN --mount` proposal will truly solve the problem.  A Dockerfile may be built on a Windows machine, a Mac, or a Linux machine.  The mount destination for MVN_REPO is a decision for the runner/builder, not the Dockerfile.

One idea that I can imagine is to declare a volume mount requirement.  Imagine something like: `REQUIRED_VOLUME MVN_REPO` is declared that essentially says, *Volume MVN_REPO needs to be defined.* Then, that logical volume may be used in the Docker build (or run).  If the volume is not defined, it could error out.  I could see this feature useful for all sorts of reasons, like declaring a destination for log files or database content.

**Comment by sixcorners** [comment]
Try using this
```Dockerfile
FROM maven
WORKDIR /usr/src/app
ENV MAVEN_OPTS=-Dmaven.repo.local=../m2repo/
COPY pom.xml .
RUN mvn -B -e -C -T 1C dependency:go-offline verify
COPY . .
RUN mvn -B -e -o -T 1C verify
```
It caches the local repo like how the [python onbuild Dockerfile](https://github.com/docker-library/python/blob/f12c2df135aef8c3f645d90aae582b2c65dbc3b5/3.6/jessie/onbuild/Dockerfile) does it. MAVEN_OPTS is needed because someone made /root/.m2/ a volume so stuff that goes in there doesn't get saved. verify is needed because "dependency:go-offline" doesn't work. You could probably just omit the "dependency:go-offline" part.
This sets it up so that changes to the pom.xml result in cache invalidation and redownload but other changes can just use the cache.

**Comment by Algram** [comment]
@sixcorners I am trying to do exactly the same thing you are doing, but for some reason my maven offline install fails and says it can't find the POM.xml for some maven internal projects. Have you had a similar problem?

**Comment by carlossg** [comment]
Now that .m2 is no longer a volume this should work

```
FROM maven:alpine
WORKDIR /usr/src/app
COPY pom.xml .
RUN mvn -B -e -C -T 1C org.apache.maven.plugins:maven-dependency-plugin:3.0.2:go-offline
COPY . .
RUN mvn -B -e -o -T 1C verify

FROM openjdk:alpine
COPY --from=0 /usr/src/app/target/*.jar ./
```
