### ISSUE TITLE
Maven Proxy Not Work since 3.9.0

### ISSUE THREAD

**Issue by c85645** [carlossg/docker-maven#490]
Hi 

When I use GitLab to run CI/CD, I find that the Maven proxy does not work since version 3.9.0, but it works in 3.8.x.
Here is my simple code in .gitlab-ci.yml
`mvn -Dhttps.proxyHost=$PROXY_HOST -Dhttps.proxyPort=$PROXY_PORT -Dhttp.proxyHost=$PROXY_HOST -Dhttp.proxyPort=$PROXY_PORT clean package`
In version 3.9.0, it causes a connection timeout due to the proxy not working.
In version 3.8.8, it works.

These are the image versions I tested:
`image: maven:3.9.8-amazoncorretto-11`
`image: maven:3.8.8-amazoncorretto-11`

**Comment by carlossg** [comment]
is it a problem with the docker image or with maven itself?

**Comment by esgn** [comment]
Same problem here. Was using `docker build --build-arg MAVEN_OPTS="-Dhttp.proxyHost=..." .` with old official maven docker images. This does not work anymore with recent images. The issue is on the maven side. Here is a recent thread on that subject https://gitlab.com/to-be-continuous/maven/-/issues/39
Safest way (thought not the easiest) to deal with this might be to stick to `settings.xml` for passing corporate proxy information.
